# Generated by Django 4.2.6 on 2023-11-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
