# Generated by Django 4.2.6 on 2023-11-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='hours',
            field=models.IntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
