# Generated by Django 4.2.6 on 2023-11-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_plan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
