# Generated by Django 4.2.6 on 2023-11-26 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0020_hour_plan_remove_habit_id_remove_habit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time_a_day',
            field=models.DurationField(default=datetime.timedelta(minutes=15)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 15, 37, 19, 74787, tzinfo=datetime.timezone.utc)),
        ),
    ]
