# Generated by Django 4.2.6 on 2023-11-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0021_plan_time_a_day_alter_habit_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cal.plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='cal.hour'),
        ),
    ]
