# Generated by Django 4.2.6 on 2023-11-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0022_remove_habit_due_date_alter_event_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('start_time_monday', models.TimeField(blank=True, null=True)),
                ('end_time_monday', models.TimeField(blank=True, null=True)),
                ('start_time_tuesday', models.TimeField(blank=True, null=True)),
                ('end_time_tuesday', models.TimeField(blank=True, null=True)),
                ('start_time_wednesday', models.TimeField(blank=True, null=True)),
                ('end_time_wednesday', models.TimeField(blank=True, null=True)),
                ('start_time_thursday', models.TimeField(blank=True, null=True)),
                ('end_time_thursday', models.TimeField(blank=True, null=True)),
                ('start_time_friday', models.TimeField(blank=True, null=True)),
                ('end_time_friday', models.TimeField(blank=True, null=True)),
                ('start_time_saturday', models.TimeField(blank=True, null=True)),
                ('end_time_saturday', models.TimeField(blank=True, null=True)),
                ('start_time_sunday', models.TimeField(blank=True, null=True)),
                ('end_time_sunday', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('time_a_day', models.DurationField()),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='cal.defaulthour')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultHabit',
            fields=[
                ('defaultplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cal.defaultplan')),
            ],
            bases=('cal.defaultplan',),
        ),
        migrations.CreateModel(
            name='DefaultTask',
            fields=[
                ('defaultplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cal.defaultplan')),
                ('due_date', models.DateField()),
            ],
            bases=('cal.defaultplan',),
        ),
    ]
