# Generated by Django 4.2.6 on 2023-11-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0023_defaulthour_defaultplan_defaulthabit_defaulttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultplan',
            name='hour',
        ),
    ]
